SELECT * FROM FLIGHT

UPDATE FLIGHT
SET STATUS = 'Completed'
WHERE FLIGHT_NO = 'F100'

UPDATE FLIGHT
SET STATUS = 'Cancelled'
WHERE FLIGHT_NO = 'F101'

SELECT * FROM BOOKING

UPDATE BOOKING
SET PRICE = PRICE + (PRICE * 0.1)
WHERE CLASS = 'Economy'

SELECT * FROM PASSENGER

UPDATE PASSENGER
SET PHONE = '121212'
WHERE NATIONAL_ID = 'P1'

SELECT * FROM CREW_MEMBER

UPDATE CREW_MEMBER
SET CREW_ROLE = 'Co-Pilot'
WHERE LICENSE_NO = 'C5'