CREATE DATABASE Airline;

USE Airline;

CREATE TABLE AIRPORT (
IATA VARCHAR (3) PRIMARY KEY NOT NULL,

AIRNAME VARCHAR (50) NOT NULL,

CITY VARCHAR (50) NOT NULL,

COUNTRY VARCHAR (50) NOT NULL
);

CREATE TABLE AIRCRAFT (
REG_NO VARCHAR (50) PRIMARY KEY NOT NULL,

MODEL VARCHAR (50) NOT NULL,

Manufacturer VARCHAR (50) NOT NULL,

Seat_Capacity INT NOT NULL,
CHECK (Seat_Capacity > 0),

Year_Manufacture INT NOT NULL
);

CREATE TABLE PASSENGER (
NATIONAL_ID VARCHAR (50) PRIMARY KEY NOT NULL,

FULL_NAME VARCHAR (50) NOT NULL,

EMAIL VARCHAR (50) UNIQUE NOT NULL,

PHONE VARCHAR (50) NOT NULL,

NATIONALITY VARCHAR (50) NOT NULL,

DATE_OF_BIRTH DATE NOT NULL
);

CREATE TABLE FLIGHT (
FLIGHT_NO VARCHAR (50) PRIMARY KEY NOT NULL,

DEPARTURE_DATE_TIME DATETIME NOT NULL,

ARRIVAL_DATE_TIME DATETIME NOT NULL,
CHECK (ARRIVAL_DATE_TIME > DEPARTURE_DATE_TIME),

STATUS VARCHAR (50) NOT NULL DEFAULT 'Scheduled',
CHECK (STATUS IN ('Scheduled','Delayed','Cancelled','Completed')),

AIRCRAFT_REG_NO VARCHAR (50),
FOREIGN KEY (AIRCRAFT_REG_NO)
REFERENCES AIRCRAFT(REG_NO)
ON DELETE CASCADE
ON UPDATE CASCADE,

FROM_IATA VARCHAR (3),
FOREIGN KEY (FROM_IATA)
REFERENCES AIRPORT(IATA)
ON DELETE CASCADE
ON UPDATE CASCADE,

TO_IATA VARCHAR (3),
FOREIGN KEY (TO_IATA)
REFERENCES AIRPORT(IATA)
ON DELETE NO ACTION
ON UPDATE NO ACTION
);

CREATE TABLE BOOKING (
BOOKING_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,

FLIGHT_NO VARCHAR (50),
FOREIGN KEY (FLIGHT_NO)
REFERENCES FLIGHT(FLIGHT_NO)
ON DELETE CASCADE
ON UPDATE CASCADE,

NATIONAL_ID VARCHAR (50),
FOREIGN KEY (NATIONAL_ID)
REFERENCES PASSENGER(NATIONAL_ID)
ON DELETE CASCADE
ON UPDATE CASCADE,

SEAT_NO VARCHAR (50) NOT NULL,

CLASS VARCHAR (50),
CHECK (CLASS IN ('Economy','Business','First')),

PRICE DECIMAL (10,2),
CHECK (PRICE > 0),

BOOKING_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CREW_MEMBER (
LICENSE_NO VARCHAR (50) PRIMARY KEY,

FULL_NAME VARCHAR (50),

CREW_ROLE VARCHAR (50),
CHECK (CREW_ROLE IN ('Pilot','Co-Pilot','Flight Attendant','Engineer'))
);

CREATE TABLE FLIGHT_CREW (
FLIGHT_NO VARCHAR (50),
FOREIGN KEY (FLIGHT_NO)
REFERENCES FLIGHT(FLIGHT_NO)
ON DELETE CASCADE
ON UPDATE CASCADE,

LICENSE_NO VARCHAR (50),
FOREIGN KEY (LICENSE_NO)
REFERENCES CREW_MEMBER(LICENSE_NO)
ON DELETE CASCADE
ON UPDATE CASCADE,

PRIMARY KEY (FLIGHT_NO, LICENSE_NO)
);