SELECT * FROM FLIGHT
ORDER BY DEPARTURE_DATE_TIME

SELECT * FROM PASSENGER
ORDER BY FULL_NAME

SELECT * FROM AIRCRAFT
ORDER BY Seat_Capacity DESC

SELECT DISTINCT CLASS FROM BOOKING

SELECT * FROM FLIGHT
WHERE STATUS = 'Cancelled' OR STATUS = 'Delayed'

SELECT * FROM PASSENGER
WHERE NATIONALITY = 'Omani'

SELECT * FROM AIRPORT
ORDER BY COUNTRY