SELECT FLIGHT_NO AS 'FLIGHT NUMBER', FROM_IATA AS 'FROM', TO_IATA AS 'TO' FROM FLIGHT

SELECT FULL_NAME AS 'PASSENGER NAME' , FLIGHT_NO AS 'FLIGHT NUMBER' FROM BOOKING B, PASSENGER P
WHERE B.NATIONAL_ID = P.NATIONAL_ID


SELECT * FROM CREW_MEMBER
SELECT * FROM FLIGHT_CREW
SELECT FULL_NAME AS 'CREW NAME' FROM FLIGHT_CREW F, CREW_MEMBER C
WHERE F.FLIGHT_NO = 'F103' AND F.LICENSE_NO = C.LICENSE_NO

SELECT * FROM FLIGHT
SELECT * FROM AIRCRAFT

SELECT * FROM FLIGHT F, AIRCRAFT A
WHERE STATUS = 'Completed' AND F.AIRCRAFT_REG_NO = A.REG_NO

SELECT * FROM PASSENGER
SELECT * FROM BOOKING

SELECT FULL_NAME , COUNT(B.NATIONAL_ID) FROM BOOKING B, PASSENGER P
WHERE B.NATIONAL_ID = P.NATIONAL_ID
GROUP BY P.FULL_NAME
ORDER BY COUNT(B.NATIONAL_ID) DESC

SELECT CLASS , SUM(PRICE) FROM BOOKING
GROUP BY CLASS

SELECT AIRCRAFT_REG_NO , COUNT(AIRCRAFT_REG_NO) FROM FLIGHT
GROUP BY (AIRCRAFT_REG_NO)

SELECT FLIGHT_NO FROM FLIGHT
WHERE STATUS = 'Completed'
GROUP BY FLIGHT_NO
HAVING COUNT(FLIGHT_NO) > 1

SELECT B.* , P.FULL_NAME , F.FROM_IATA , F.TO_IATA FROM BOOKING B, PASSENGER P , FLIGHT F , AIRPORT A , AIRPORT A2
WHERE B.NATIONAL_ID = P.NATIONAL_ID 
AND B.FLIGHT_NO = F.FLIGHT_NO 
AND F.FROM_IATA = A.IATA
AND F.TO_IATA = A2.IATA

