CREATE DATABASE Company

CREATE TABLE EMPLOYEE (
SSN INT PRIMARY KEY,  
FNAME VARCHAR, 
LNAME VARCHAR, 
BIRTH_DATE DATE, 
GENDER VARCHAR,);

CREATE TABLE DEPARTMENT (DNUM INT PRIMARY KEY, DNAME VARCHAR);

CREATE TABLE LOCATIONS (LOCATION_ID INT PRIMARY KEY, LOCATION_NAME VARCHAR);

CREATE TABLE DEPENDENTS (DT_NAME VARCHAR PRIMARY KEY ,GENDER VARCHAR, BIRTH_DATA DATE);

CREATE TABLE PROJECT (PNUM INT PRIMARY KEY, PNAME VARCHAR, LOCATION_NAME VARCHAR);

CREATE TABLE WORKING_PROJECT (
PNUM INT,
CONSTRAINT PNUM
FOREIGN KEY (PNUM)
REFERENCES PROJECT(PNUM),
SSN INT,
CONSTRAINT SSN
FOREIGN KEY (SSN)
REFERENCES EMPLOYEE(SSN),
WORKING_HOURS INT);

ALTER TABLE EMPLOYEE ADD SUPERVISOR_ID INT CONSTRAINT SUPERVISOR_ID FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN)

ALTER TABLE EMPLOYEE ADD DNUM INT CONSTRAINT DNUM FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUM)

ALTER TABLE DEPARTMENT 
ADD LOCATION_ID INT 
CONSTRAINT LOCATION_ID 
FOREIGN KEY (LOCATION_ID) 
REFERENCES LOCATIONS(LOCATION_ID)

ALTER TABLE DEPARTMENT 
ADD SSN INT 
CONSTRAINT DMANEGER 
FOREIGN KEY (SSN) 
REFERENCES EMPLOYEE(SSN)

ALTER TABLE DEPARTMENT 
ADD HIRE_DATE DATE

ALTER TABLE DEPENDENTS 
ADD SSN INT 
CONSTRAINT DSSN 
FOREIGN KEY (SSN) 
REFERENCES EMPLOYEE(SSN)

ALTER TABLE PROJECT 
ADD DNUM INT 
CONSTRAINT DNUMBER 
FOREIGN KEY (DNUM) 
REFERENCES DEPARTMENT(DNUM)