SELECT DrID FROM APPOINTMENT
GROUP BY DrID
HAVING COUNT(*) > 1

SELECT SERVICE_ID FROM APPOINTMENT_SERVICE
GROUP BY SERVICE_ID
HAVING COUNT(*) > 2

SELECT DID FROM DOCTOR
GROUP BY DID
HAVING COUNT(DID) > 1

SELECT PAYMENT_STATUS FROM BILLING
WHERE TOTAL_AMOUNT > 50

SELECT TOP 1 SERVICE_ID,COUNT(SERVICE_ID) FROM APPOINTMENT_SERVICE
GROUP BY SERVICE_ID
ORDER BY COUNT(SERVICE_ID) DESC


SELECT * FROM SERV
SELECT * FROM APPOINTMENT_SERVICE
SELECT * FROM SERV , APPOINTMENT_SERVICE

SELECT SERVICES_NAME AS "HIGHEST", QUANTITY FROM SERV , APPOINTMENT_SERVICE
GROUP BY SERVICES_NAME



-- This is Really Hard to Think

SELECT TOP 1 S.SERVICE_ID, SUM(AC.QUANTITY * UNIT_PRICE) as revenue FROM APPOINTMENT_SERVICE AC
JOIN SERV S ON S.SERVICE_ID = AC.SERVICE_ID
GROUP BY S.SERVICE_ID
order by revenue desc

