SELECT COUNT(*) FROM PATIENT

SELECT COUNT(*) FROM DOCTOR

SELECT COUNT(*) FROM APPOINTMENT

SELECT * FROM BILLING
SELECT SUM(TOTAL_AMOUNT) FROM BILLING

SELECT * FROM SERV
SELECT AVG(UNIT_PRICE) FROM SERV

SELECT MAX(UNIT_PRICE),MIN(UNIT_PRICE) FROM SERV