SELECT COUNT(DrID) FROM DOCTOR
GROUP BY DID

SELECT COUNT(AID) FROM APPOINTMENT
GROUP BY DrID

SELECT COUNT(AID) FROM APPOINTMENT
GROUP BY APPO_STATUS

SELECT * FROM BILLING

SELECT SUM(TOTAL_AMOUNT) FROM BILLING
GROUP BY PAYMENT_STATUS

SELECT AVG(UNIT_PRICE) FROM SERV
GROUP BY SERVICE_TYPE

SELECT * FROM APPOINTMENT_SERVICE

SELECT SUM(QUANTITY) FROM APPOINTMENT_SERVICE
GROUP BY SERVICE_ID