SELECT * FROM APPOINTMENT

DELETE FROM APPOINTMENT_SERVICE
WHERE AID = 5

DELETE FROM APPOINTMENT
WHERE APPO_STATUS = 'Cancelled'


SELECT * FROM SERV
SELECT * FROM APPOINTMENT_SERVICE

DELETE FROM SERV
WHERE SERVICE_ID = 7

SELECT * FROM BILLING

DELETE FROM BILLING 
WHERE PAYMENT_METHOD = 'Insurance'