DROP DATABASE HOSPITAL;
CREATE DATABASE HOSPITAL;

CREATE TABLE PATIENT (
PID INT PRIMARY KEY,
PNAME VARCHAR,
AGE INT,
GENDER VARCHAR,
PHONE_NUM INT,
DOB DATE,
BLOODG VARCHAR
);

CREATE TABLE DOCTOR (
DrID INT PRIMARY KEY,
Dr_NAME VARCHAR,
SPECIALTY VARCHAR,
);

CREATE TABLE DEPARTMENT (
DID INT PRIMARY KEY,
DNAME VARCHAR
);

ALTER TABLE DEPARTMENT ADD DEPT_HEAD INT CONSTRAINT DEPT_HEAD_FK FOREIGN KEY (DEPT_HEAD) REFERENCES DOCTOR(DrID);

ALTER TABLE DOCTOR ADD DID INT CONSTRAINT DEPT_ID FOREIGN KEY (DID) REFERENCES DEPARTMENT(DID);

CREATE TABLE SER (
SNAME VARCHAR PRIMARY KEY,
STYPE VARCHAR,
PRICE INT
);

CREATE TABLE MEDICAL_RECORD (
MID INT PRIMARY KEY,
DIAGNOSIS VARCHAR,
TREATMENT VARCHAR,
PID INT,
CONSTRAINT PATIENT_ID
FOREIGN KEY (PID)
REFERENCES PATIENT(PID)
);

CREATE TABLE CREATE_RECORD (
MID INT,
CONSTRAINT MEDICAL_RECORD_FK
FOREIGN KEY (MID)
REFERENCES MEDICAL_RECORD(MID),
DrID INT,
CONSTRAINT DOCTOR_ID
FOREIGN KEY (DrID)
REFERENCES DOCTOR(DrID),
);

CREATE TABLE APPOINTMENT (
AID INT PRIMARY KEY,
DT DATE,
TM TIME,
TYP VARCHAR,
STUS VARCHAR,
PID INT,
CONSTRAINT PAT_ID
FOREIGN KEY (PID)
REFERENCES PATIENT(PID),
SNAME VARCHAR,
CONSTRAINT SER_NAME
FOREIGN KEY (SNAME)
REFERENCES SER(SNAME)
);

CREATE TABLE HANDEL_APPOINTMENT (
AID INT,
CONSTRAINT APPOINTMENT_ID
FOREIGN KEY (AID)
REFERENCES APPOINTMENT(AID),
DrID INT,
CONSTRAINT DR_ID
FOREIGN KEY (DrID)
REFERENCES DOCTOR(DrID),
);

CREATE TABLE BILLING (
PAYMENT_ID INT PRIMARY KEY,
DT DATE,
TM TIME,
PRICE INT,
AID INT,
CONSTRAINT APPO_ID
FOREIGN KEY (AID)
REFERENCES APPOINTMENT(AID),
SNAME VARCHAR,
CONSTRAINT SERV_NAME
FOREIGN KEY (SNAME)
REFERENCES SER(SNAME),
PID INT,
CONSTRAINT PATIENT_FK
FOREIGN KEY (PID)
REFERENCES PATIENT(PID),
);