CREATE DATABASE HOSPITAL;

USE HOSPITAL

CREATE TABLE PATIENT (
PID INT PRIMARY KEY,
F_NAME VARCHAR(100),
L_NAME VARCHAR(100),
DOB DATE,
AGE INT,
GENDER VARCHAR(100),
BLOOD_GROUP VARCHAR(100),
PHONE_NO INT,
EMAIL VARCHAR(100),
ADDRESSS VARCHAR(100)
);

CREATE TABLE DEPARTMENT (
DID INT PRIMARY KEY,
DNAME VARCHAR(100),
CONTACT_NO INT,
NO_OF_DOCTORS INT
);

CREATE TABLE SERV (
SERVICE_ID INT PRIMARY KEY,
SERVICES_NAME VARCHAR(100),
DESCRIPTIONS TEXT,
SERVICE_TYPE VARCHAR(100),
UNIT_PRICE DECIMAL
);

CREATE TABLE DOCTOR (
DrID INT PRIMARY KEY,
Dr_NAME VARCHAR(100),
SPECIALITY VARCHAR(100),
PHONE_NO INT,
EMAIL VARCHAR(100),
LICENSE_NO VARCHAR(100),
QUALIFICATION VARCHAR(100),
YEARS_OF_EXP INT,
DID INT,
CONSTRAINT DID
FOREIGN KEY (DID)
REFERENCES DEPARTMENT(DID)
);

CREATE TABLE APPOINTMENT (
AID INT PRIMARY KEY,
PID INT,
DrID INT,
APPO_DATE DATE,
APPO_TIME TIME,
REASON VARCHAR(100),
APPO_TYPE VARCHAR(100),
APPO_STATUS VARCHAR(100),
CONSTRAINT PATIENT_ID
FOREIGN KEY (PID)
REFERENCES PATIENT(PID),
CONSTRAINT DOCTOR_ID
FOREIGN KEY (DrID)
REFERENCES DOCTOR(DrID)
);

CREATE TABLE BILLING (
BILL_ID INT PRIMARY KEY,
PID INT,
AID INT,
BILL_DATE DATE,
TOTAL_AMOUNT DECIMAL,
PAYMENT_STATUS VARCHAR(100),
PAYMENT_METHOD VARCHAR(100),
DUE_DATE DATE,
FOREIGN KEY (PID)
REFERENCES PATIENT(PID),
CONSTRAINT APPOINTMENT_ID
FOREIGN KEY (AID)
REFERENCES APPOINTMENT(AID),
);

CREATE TABLE MEDICAL_RECORD (
MID INT PRIMARY KEY,
PID INT,
DrID INT,
AID INT,
DIAGNOSIS VARCHAR(100),
VISIT_DATE DATE,
PRESCIBED_MEDICATIONS TEXT,
DOCTOR_NOTES TEXT,
TREATMENT_PLAN TEXT,
FOLLOW_UP_REQUIRED BIT,
FOREIGN KEY (PID)
REFERENCES PATIENT(PID),
FOREIGN KEY (DrID)
REFERENCES DOCTOR(DrID),
FOREIGN KEY (AID)
REFERENCES APPOINTMENT(AID),
);

CREATE TABLE APPOINTMENT_SERVICE (
AID INT,
SERVICE_ID INT,
QUANTITY INT,
FOREIGN KEY (AID)
REFERENCES APPOINTMENT(AID),
FOREIGN KEY (SERVICE_ID)
REFERENCES SERV(SERVICE_ID)
);