SELECT F_NAME + ' ' + L_NAME AS NAME,APPO_DATE FROM PATIENT P, APPOINTMENT A
WHERE P.PID = A.PID

SELECT Dr_NAME, DNAME FROM DOCTOR D, DEPARTMENT DP
WHERE D.DID = DP.DID

SELECT AID , APPO_STATUS , F_NAME FROM APPOINTMENT A , PATIENT P
WHERE P.PID = A.PID

SELECT AID , Dr_NAME, APPO_STATUS FROM APPOINTMENT A , DOCTOR D
WHERE A.DrID = D.DrID


ALTER TABLE SERV
ADD DID INT;

ALTER TABLE SERV
ADD CONSTRAINT FK_SERV_DEPARTMENT
FOREIGN KEY (DID)
REFERENCES Department(DID);

UPDATE SERV SET DID = 4 WHERE SERVICE_ID = 1;
UPDATE SERV SET DID = 1 WHERE SERVICE_ID = 2;
UPDATE SERV SET DID = 2 WHERE SERVICE_ID = 3;
UPDATE SERV SET DID = 3 WHERE SERVICE_ID = 4;
UPDATE SERV SET DID = 4 WHERE SERVICE_ID = 5;
UPDATE SERV SET DID = 3 WHERE SERVICE_ID = 6;
UPDATE SERV SET DID = 4 WHERE SERVICE_ID = 7;

SELECT SERVICES_NAME, UNIT_PRICE, DNAME FROM SERV S, DEPARTMENT D
WHERE D.DID = DP.DID

SELECT * FROM APPOINTMENT
WHERE APPO_STATUS = 'Completed'

SELECT Dr_NAME , DNAME FROM DOCTOR D , DEPARTMENT DT
WHERE D.DID = DT.DID AND DNAME = 'Cardiology'

SELECT * FROM SERV
WHERE UNIT_PRICE > 20

SELECT F_NAME + ' ' + L_NAME AS NAME, Dr_NAME , APPO_DATE FROM PATIENT P , DOCTOR D , APPOINTMENT A
WHERE P.PID = A.PID

SELECT F_NAME + ' ' + L_NAME AS NAME, APPO_STATUS , DNAME FROM PATIENT P , DEPARTMENT D , APPOINTMENT A
WHERE P.PID = A.PID

SELECT F_NAME + ' ' + L_NAME AS NAME, SERVICES_NAME , QUANTITY FROM PATIENT P , SERV S , APPOINTMENT_SERVICE A
WHERE S.SERVICE_ID = A.SERVICE_ID

SELECT F_NAME + ' ' + L_NAME AS NAME, Dr_NAME , SERVICES_NAME , APPO_DATE FROM PATIENT P , DOCTOR D , SERV S , APPOINTMENT A
WHERE P.PID = A.PID

