UPDATE APPOINTMENT
SET APPO_STATUS = 'Completed'
WHERE APPO_STATUS = 'Scheduled'

SELECT * FROM BILLING

UPDATE BILLING
SET PAYMENT_STATUS = 'Paid'
WHERE BILL_ID = 5

SELECT * FROM SERV

UPDATE SERV
SET UNIT_PRICE =(UNIT_PRICE) + (UNIT_PRICE) * 0.1

SELECT * FROM PATIENT

UPDATE PATIENT
SET PHONE_NO = 98765432
WHERE PID = 1

SELECT * FROM DOCTOR

UPDATE DOCTOR
SET DID = 2
WHERE DrID = 1