
CREATE TABLE DEPARTURE_GATE (
GATE_CODE VARCHAR (50) PRIMARY KEY,

TERMINAL_NAME VARCHAR (50),

AIRPORT_IATA VARCHAR (3),
FOREIGN KEY (AIRPORT_IATA)
REFERENCES AIRPORT(IATA)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE AIRLINE_OPERATOR (
IATA VARCHAR (50) PRIMARY KEY,

FULL_NAME VARCHAR (50),

COUNTRY_REG VARCHAR (50),

EMAIL VARCHAR (50)
);

CREATE TABLE BAGGAGE (
TAG_NUMBER VARCHAR (50) PRIMARY KEY,

B_TYPE VARCHAR (50),
CHECK (B_TYPE IN ('Cabin','Checked')),

WEIGHT_KG DECIMAL,

BOOKING_ID INT,
FOREIGN KEY (BOOKING_ID)
REFERENCES BOOKING(BOOKING_ID)
);

CREATE TABLE FLIGHT_DELAY (
DELAY_ID INT PRIMARY KEY,

FLIGHT_NO VARCHAR (50),
FOREIGN KEY (FLIGHT_NO)
REFERENCES FLIGHT(FLIGHT_NO),

DATETIME_RECORDED DATETIME,

DURATION_M INT,

REASON VARCHAR (50)
);