SELECT * FROM DEPARTURE_GATE
SELECT * FROM FLIGHT_DELAY


SELECT  F.AIRLINE_IATA, COUNT(DISTINCT B.FLIGHT_NO) AS 'TOTAL FLIGHTS', COUNT(B.NATIONAL_ID) AS 'TOTAL PASSENGERS', SUM(B.PRICE) AS 'TOTAL REVENUE' FROM FLIGHT F, BOOKING B
WHERE F.FLIGHT_NO = B.FLIGHT_NO
GROUP BY F.AIRLINE_IATA


SELECT TOP 1 F.GATE_CODE, COUNT(F.GATE_CODE), DG.TERMINAL_NAME, DG.AIRPORT_IATA FROM FLIGHT F, DEPARTURE_GATE DG
GROUP BY F.GATE_CODE, DG.TERMINAL_NAME, DG.AIRPORT_IATA
ORDER BY COUNT(F.GATE_CODE) DESC


SELECT FD.FLIGHT_NO, AO.FULL_NAME, COUNT(FD.FLIGHT_NO), SUM(FD.DURATION_M) FROM FLIGHT_DELAY FD, FLIGHT F, AIRLINE_OPERATOR AO
WHERE FD.FLIGHT_NO = F.FLIGHT_NO
AND F.AIRLINE_IATA = AO.IATA
GROUP BY FD.FLIGHT_NO, AO.FULL_NAME



SELECT * FROM BAGGAGE
SELECT * FROM PASSENGER

SELECT P.FULL_NAME, COUNT(BG.TAG_NUMBER) AS 'NUMBER OF BAGGAGES', BG.B_TYPE AS 'BAG TYPE' FROM PASSENGER P, BAGGAGE BG, BOOKING B
WHERE P.NATIONAL_ID = B.NATIONAL_ID
AND B.BOOKING_ID = BG.BOOKING_ID
GROUP BY P.FULL_NAME, BG.B_TYPE


SELECT * FROM FLIGHT
SELECT * FROM AIRLINE_OPERATOR
SELECT * FROM BOOKING

SELECT F.FLIGHT_NO, F.FROM_IATA, F.TO_IATA, SUM(PRICE) AS 'TOTAL REVENUE' FROM AIRLINE_OPERATOR AO, FLIGHT F, BOOKING B
WHERE AO.IATA = F.AIRLINE_IATA
AND F.FLIGHT_NO = B.FLIGHT_NO
AND AO.COUNTRY_REG = 'Oman'
GROUP BY F.FLIGHT_NO, F.FROM_IATA, F.TO_IATA


SELECT F.FLIGHT_NO, AO.FULL_NAME, F.GATE_CODE, F.FROM_IATA, F.TO_IATA, COUNT(B.NATIONAL_ID) AS 'TOTAL PASENGERS', COUNT(BG.TAG_NUMBER) AS 'TOTAL BAGS', SUM(FD.DURATION_M) AS 'TOTAL DELAY', SUM(B.PRICE) AS 'TOTAL REVENUE' FROM FLIGHT F, AIRLINE_OPERATOR AO, BOOKING B, BAGGAGE BG, FLIGHT_DELAY FD
WHERE F.AIRLINE_IATA = AO.IATA
AND F.FLIGHT_NO = B.FLIGHT_NO
AND B.BOOKING_ID = BG.BOOKING_ID
AND F.FLIGHT_NO = FD.FLIGHT_NO
GROUP BY F.FLIGHT_NO, AO.FULL_NAME, F.GATE_CODE, F.FROM_IATA, F.TO_IATA
ORDER BY SUM(B.PRICE) DESC