SELECT * FROM AIRLINE_OPERATOR
ORDER BY FULL_NAME 

SELECT * FROM DEPARTURE_GATE

SELECT * FROM BAGGAGE
ORDER BY WEIGHT_KG DESC

SELECT * FROM FLIGHT_DELAY
ORDER BY DATETIME_RECORDED

SELECT * FROM FLIGHT
WHERE GATE_CODE = 'NULL'