SELECT F.FLIGHT_NO,  A.FULL_NAME, F.GATE_CODE FROM FLIGHT F, AIRLINE_OPERATOR A
WHERE F.AIRLINE_IATA = A.IATA


SELECT BG.* ,P.FULL_NAME ,B.FLIGHT_NO FROM BAGGAGE BG, BOOKING B, PASSENGER P
WHERE BG.BOOKING_ID = B.BOOKING_ID
AND B.NATIONAL_ID = P.NATIONAL_ID


SELECT BG.BOOKING_ID ,P.FULL_NAME ,COUNT(BG.TAG_NUMBER) FROM BAGGAGE BG, BOOKING B, PASSENGER P
WHERE BG.BOOKING_ID = B.BOOKING_ID
AND B.NATIONAL_ID = P.NATIONAL_ID
GROUP BY BG.BOOKING_ID, P.FULL_NAME


SELECT FD.* ,AO.FULL_NAME FROM FLIGHT_DELAY FD, AIRLINE_OPERATOR AO ,FLIGHT F
WHERE FD.FLIGHT_NO = F.FLIGHT_NO
AND F.AIRLINE_IATA = AO.IATA


SELECT B.FLIGHT_NO ,SUM(BG.WEIGHT_KG) AS 'TOTAL WEIGHT' FROM BAGGAGE BG ,BOOKING B
WHERE BG.BOOKING_ID = B.BOOKING_ID
AND BG.B_TYPE = 'Checked'
GROUP BY B.FLIGHT_NO


SELECT AIRLINE_IATA ,COUNT(AIRLINE_IATA) FROM FLIGHT
GROUP BY AIRLINE_IATA
ORDER BY COUNT(AIRLINE_IATA) DESC


SELECT FLIGHT_NO, COUNT(FLIGHT_NO) FROM FLIGHT_DELAY
GROUP BY FLIGHT_NO
HAVING COUNT(FLIGHT_NO) > 1