ALTER TABLE FLIGHT
ADD AIRLINE_IATA VARCHAR (50),
GATE_CODE VARCHAR (50)

ALTER TABLE FLIGHT
ADD FOREIGN KEY (AIRLINE_IATA) REFERENCES AIRLINE_OPERATOR(IATA) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (GATE_CODE) REFERENCES DEPARTURE_GATE(GATE_CODE) ON DELETE NO ACTION ON UPDATE NO ACTION

ALTER TABLE Flight
DROP CONSTRAINT FK__FLIGHT__GATE_COD__5812160E;


ALTER TABLE FLIGHT
DROP COLUMN AIRLINE_IATA , GATE_CODE

SELECT * FROM FLIGHT