SELECT * FROM FLIGHT

DELETE FROM FLIGHT
WHERE FLIGHT_NO = 'F101'

SELECT * FROM BOOKING

DELETE FROM BOOKING
WHERE BOOKING_ID = '11'

SELECT * FROM PASSENGER

DELETE FROM PASSENGER
WHERE NATIONAL_ID = 'P7'

-- THE CASCADE DELETE HAS DELETED THE PASSENGER AND HIS BOOKING DETAILS FROM BOTH TABLES (PASSENGER , BOOKING).


