SELECT F.FLIGHT_NO , F.FROM_IATA , F.TO_IATA , AC.MODEL , COUNT(B.FLIGHT_NO) AS 'NUMBER OF PASSENGERS' FROM FLIGHT F , AIRPORT A , AIRPORT A2 ,AIRCRAFT AC , BOOKING B
WHERE F.FROM_IATA = A.IATA 
AND F.TO_IATA = A2.IATA
AND F.AIRCRAFT_REG_NO = AC.REG_NO 
AND F.FLIGHT_NO = B.FLIGHT_NO

GROUP BY F.FLIGHT_NO , F.FROM_IATA , F.TO_IATA , AC.MODEL

SELECT P.* FROM BOOKING B, PASSENGER P
WHERE B.NATIONAL_ID = P.NATIONAL_ID

SELECT DISTINCT  P.* FROM BOOKING B,PASSENGER P
WHERE P.NATIONAL_ID NOT IN (SELECT NATIONAL_ID FROM BOOKING)

SELECT FLIGHT_NO , SUM(PRICE) FROM BOOKING
GROUP BY FLIGHT_NO
HAVING SUM(PRICE) > 500


SELECT C.FULL_NAME , COUNT(F.LICENSE_NO) FROM FLIGHT_CREW F, CREW_MEMBER C
WHERE C.LICENSE_NO = F.LICENSE_NO
GROUP BY C.FULL_NAME
HAVING COUNT(F.LICENSE_NO) > 1

SELECT AVG(PRICE) FROM BOOKING

SELECT CLASS , AVG(PRICE) FROM BOOKING
GROUP BY CLASS
HAVING AVG(PRICE) > (SELECT AVG(PRICE) FROM BOOKING)

SELECT TOP 1 B.FLIGHT_NO ,F.FROM_IATA ,F.TO_IATA ,COUNT(B.FLIGHT_NO)  FROM BOOKING B, FLIGHT F
WHERE B.FLIGHT_NO = F.FLIGHT_NO
GROUP BY B.FLIGHT_NO ,F.FROM_IATA ,F.TO_IATA
ORDER BY B.FLIGHT_NO ASC


SELECT SUM(PRICE) ,COUNT(B.BOOKING_ID) ,AVG(PRICE) ,MAX(PRICE) ,MIN(PRICE) FROM BOOKING B
GROUP BY CLASS

SELECT P.FULL_NAME , F.FLIGHT_NO , B.BOOKING_DATE FROM FLIGHT F, BOOKING B,PASSENGER P
WHERE P.NATIONAL_ID = B.NATIONAL_ID 
AND B.FLIGHT_NO = F.FLIGHT_NO
AND F.STATUS = 'Cancelled'

SELECT FC.FLIGHT_NO, COUNT(C.LICENSE_NO) , F.DEPARTURE_DATE_TIME FROM FLIGHT_CREW FC, CREW_MEMBER C , FLIGHT F
WHERE FC.LICENSE_NO = C.LICENSE_NO 
AND C.CREW_ROLE = 'Pilot' 
AND C.CREW_ROLE = 'Flight Attendant'
AND FC.FLIGHT_NO = F.FLIGHT_NO
GROUP BY FC.FLIGHT_NO , FC.FLIGHT_NO , F.DEPARTURE_DATE_TIME

SELECT F.FLIGHT_NO ,F.FROM_IATA ,F.TO_IATA, AC.MODEL, AC.Manufacturer, COUNT(B.PRICE) AS 'NUMBER OF PASSENGERS', COUNT(FC.LICENSE_NO) AS 'NUMBER OR CREW' ,SUM(PRICE) AS 'TOTAL REVENUE' FROM FLIGHT F, AIRPORT A, AIRPORT A2, AIRCRAFT AC, BOOKING B ,FLIGHT_CREW FC
WHERE F.FLIGHT_NO = B.FLIGHT_NO
AND F.FLIGHT_NO = FC.FLIGHT_NO
AND F.AIRCRAFT_REG_NO = AC.REG_NO
AND F.FROM_IATA = A.IATA
AND F.TO_IATA = A2.IATA
GROUP BY F.FLIGHT_NO ,F.FROM_IATA ,F.TO_IATA ,AC.MODEL ,AC.Manufacturer
ORDER BY SUM(B.PRICE)



